### ISSUE TITLE
noVNC & websockify in Docker Compose on Raspberry Pi 4 using RealVNC Server

### ISSUE THREAD

**Issue by wwwescape** [novnc/websockify#556]
I run a number of applications on a Raspberry Pi 4 all through Docker containers using Docker Compose.

I couldn't find an official Docker image for noVNC so I settled on `rugarci/novnc`. The Docker Compose for the noVNC container is as follows:

```
version: "2.1"
services:
  novnc:
    image: rugarci/novnc
    container_name: novnc
    ports:
      - 6080:8081
    environment:
      - REMOTE_HOST=192.168.0.125
      - REMOTE_PORT=5901
    restart: always
```

Note: The Raspberry Pi 4's IP address is `192.168.0.125`.

Once the container was up, I was successfully able to load noVNC in a browser. Next I tried connecting to the VNC server on the Raspberry Pi 4 but kept getting the `Failed to connect to server` error. I am using  RealVNC Server v7.5.1 with the security settings set to the following:

```
Encryption: Prefer off
Authentication: VNC password
```

I then uninstalled RealVNC Server and installed Tight VNC Server. Once again, I loaded noVNC in a browser at `http://192.168.0.125:6080/` and tried connecting and this time I was able to see the Raspberry Pi 4's desktop!

However, I really need to use RealVNC Server so I uninstalled Tight VNC Server and reinstalled RealVNC Server. Browsing all over the internet I came to the conclusion that I may need to use websockify. I cloned the repository and built the Docker image and attempted to composerize the Docker run command from the documentation. The Docker Compose for the websockify container is as follows:

```
version: "2.1"
services:
  websockify:
    image: novnc/websockify
    container_name: websockify
    ports:
      - 7000:80
    command:
      - '80'
      - 192.168.0.125:5901
    restart: always
```

Surprisingly, I was able to get the container up and running and then proceeded to load websockify in a browser at `http://192.168.0.125:7000/`. The page loaded with the following error:

```
Error response
Error code: 405

Message: Method Not Allowed.

Error code explanation: 405 - Specified method is invalid for this resource.
```

The Docker container logs are as follows:

```
WebSocket server settings:
  - Listen on :80
  - No SSL/TLS support (no cert file)
  - proxying from :80 to 192.168.0.125:5901
192.168.0.189 - - [08/Jul/2023 13:24:01] code 405, message Method Not Allowed
```

I'm pretty sure I 've got the port mappings wrong but there's definitely more to it. I was wondering if the `Wrap a program` section from the documentation is something I should look into but I didn't know how to add it to Docker Compose. Overall, I am confused how the whole noVNC + websockify for RealVNC Server should be set up for my use-case.

Any pointers would be much appreciated.
